'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class strings_es
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("db.strings_es", GetType(strings_es).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Details:.
        '''</summary>
        Friend Shared ReadOnly Property accDetStr() As String
            Get
                Return ResourceManager.GetString("accDetStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Actual Values.
        '''</summary>
        Friend Shared ReadOnly Property actStr() As String
            Get
                Return ResourceManager.GetString("actStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address:.
        '''</summary>
        Friend Shared ReadOnly Property addressStr() As String
            Get
                Return ResourceManager.GetString("addressStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Users.
        '''</summary>
        Friend Shared ReadOnly Property addUsers() As String
            Get
                Return ResourceManager.GetString("addUsers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Back.
        '''</summary>
        Friend Shared ReadOnly Property btnBackStr() As String
            Get
                Return ResourceManager.GetString("btnBackStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change.
        '''</summary>
        Friend Shared ReadOnly Property btnChanStr() As String
            Get
                Return ResourceManager.GetString("btnChanStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend Shared ReadOnly Property btnClose() As String
            Get
                Return ResourceManager.GetString("btnClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Friend Shared ReadOnly Property btnLogInStr() As String
            Get
                Return ResourceManager.GetString("btnLogInStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modify profile.
        '''</summary>
        Friend Shared ReadOnly Property btnModPro() As String
            Get
                Return ResourceManager.GetString("btnModPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save changes.
        '''</summary>
        Friend Shared ReadOnly Property btnSaveChanStr() As String
            Get
                Return ResourceManager.GetString("btnSaveChanStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property btnSaveStr() As String
            Get
                Return ResourceManager.GetString("btnSaveStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Image:.
        '''</summary>
        Friend Shared ReadOnly Property btnSelImg() As String
            Get
                Return ResourceManager.GetString("btnSelImg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Submit Changes.
        '''</summary>
        Friend Shared ReadOnly Property btnSubChgStr() As String
            Get
                Return ResourceManager.GetString("btnSubChgStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Password.
        '''</summary>
        Friend Shared ReadOnly Property chgPass() As String
            Get
                Return ResourceManager.GetString("chgPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change password.
        '''</summary>
        Friend Shared ReadOnly Property chgPassFormStr() As String
            Get
                Return ResourceManager.GetString("chgPassFormStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You need to set a new password for this account.
        '''</summary>
        Friend Shared ReadOnly Property chgPassStr() As String
            Get
                Return ResourceManager.GetString("chgPassStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City:.
        '''</summary>
        Friend Shared ReadOnly Property cityStr() As String
            Get
                Return ResourceManager.GetString("cityStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Information.
        '''</summary>
        Friend Shared ReadOnly Property contInfStr() As String
            Get
                Return ResourceManager.GetString("contInfStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Country:.
        '''</summary>
        Friend Shared ReadOnly Property counStr() As String
            Get
                Return ResourceManager.GetString("counStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current password.
        '''</summary>
        Friend Shared ReadOnly Property currPassStr() As String
            Get
                Return ResourceManager.GetString("currPassStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date of Birth:.
        '''</summary>
        Friend Shared ReadOnly Property dateOBStr() As String
            Get
                Return ResourceManager.GetString("dateOBStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show advanced options.
        '''</summary>
        Friend Shared ReadOnly Property dbChkBoxStr() As String
            Get
                Return ResourceManager.GetString("dbChkBoxStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password:.
        '''</summary>
        Friend Shared ReadOnly Property dbPassStr() As String
            Get
                Return ResourceManager.GetString("dbPassStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database Settings.
        '''</summary>
        Friend Shared ReadOnly Property dbSettStr() As String
            Get
                Return ResourceManager.GetString("dbSettStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado de la con. a la BBDD.
        '''</summary>
        Friend Shared ReadOnly Property dbStatusStr() As String
            Get
                Return ResourceManager.GetString("dbStatusStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database:.
        '''</summary>
        Friend Shared ReadOnly Property dbStr() As String
            Get
                Return ResourceManager.GetString("dbStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database user:.
        '''</summary>
        Friend Shared ReadOnly Property dbUserStr() As String
            Get
                Return ResourceManager.GetString("dbUserStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can&apos;t change the default user profile picture.
        '''</summary>
        Friend Shared ReadOnly Property defUserPic() As String
            Get
                Return ResourceManager.GetString("defUserPic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can&apos;t change the default user profile.
        '''</summary>
        Friend Shared ReadOnly Property defUserPro() As String
            Get
                Return ResourceManager.GetString("defUserPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image files (*.jpg, *.jpeg, *.jpe, *.jfif, *.png)|*.jpg; *.jpeg; *.jpe; *.jfif; *.png|All files (*.*) | *.*.
        '''</summary>
        Friend Shared ReadOnly Property diagFilter() As String
            Get
                Return ResourceManager.GetString("diagFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Image.
        '''</summary>
        Friend Shared ReadOnly Property diagTitle() As String
            Get
                Return ResourceManager.GetString("diagTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Salir.
        '''</summary>
        Friend Shared ReadOnly Property exitStr() As String
            Get
                Return ResourceManager.GetString("exitStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property idColStr() As String
            Get
                Return ResourceManager.GetString("idColStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image saved successfully.
        '''</summary>
        Friend Shared ReadOnly Property imgSuccStr() As String
            Get
                Return ResourceManager.GetString("imgSuccStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instance name:.
        '''</summary>
        Friend Shared ReadOnly Property instanceNameStr() As String
            Get
                Return ResourceManager.GetString("instanceNameStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Joined on:.
        '''</summary>
        Friend Shared ReadOnly Property joinStr() As String
            Get
                Return ResourceManager.GetString("joinStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Friend Shared ReadOnly Property logFormStr() As String
            Get
                Return ResourceManager.GetString("logFormStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username.
        '''</summary>
        Friend Shared ReadOnly Property loginNameColStr() As String
            Get
                Return ResourceManager.GetString("loginNameColStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Log out.
        '''</summary>
        Friend Shared ReadOnly Property logOut() As String
            Get
                Return ResourceManager.GetString("logOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level 1 - Read Only.
        '''</summary>
        Friend Shared ReadOnly Property lvl1Str() As String
            Get
                Return ResourceManager.GetString("lvl1Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level 2 - Write.
        '''</summary>
        Friend Shared ReadOnly Property lvl2Str() As String
            Get
                Return ResourceManager.GetString("lvl2Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level 3 - Add Tables.
        '''</summary>
        Friend Shared ReadOnly Property lvl3Str() As String
            Get
                Return ResourceManager.GetString("lvl3Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level 4 - User Management.
        '''</summary>
        Friend Shared ReadOnly Property lvl4Str() As String
            Get
                Return ResourceManager.GetString("lvl4Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level 5 - Administrator.
        '''</summary>
        Friend Shared ReadOnly Property lvl5Str() As String
            Get
                Return ResourceManager.GetString("lvl5Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level.
        '''</summary>
        Friend Shared ReadOnly Property lvlColStr() As String
            Get
                Return ResourceManager.GetString("lvlColStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Levels.
        '''</summary>
        Friend Shared ReadOnly Property lvlGrpStr() As String
            Get
                Return ResourceManager.GetString("lvlGrpStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manage Users.
        '''</summary>
        Friend Shared ReadOnly Property manUsers() As String
            Get
                Return ResourceManager.GetString("manUsers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Menu.
        '''</summary>
        Friend Shared ReadOnly Property menuFormStr() As String
            Get
                Return ResourceManager.GetString("menuFormStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile:.
        '''</summary>
        Friend Shared ReadOnly Property mobPhoneStr() As String
            Get
                Return ResourceManager.GetString("mobPhoneStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modify Profile.
        '''</summary>
        Friend Shared ReadOnly Property modProFormStr() As String
            Get
                Return ResourceManager.GetString("modProFormStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Computer name or IP:.
        '''</summary>
        Friend Shared ReadOnly Property nameIPstr() As String
            Get
                Return ResourceManager.GetString("nameIPstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name:.
        '''</summary>
        Friend Shared ReadOnly Property nameStr() As String
            Get
                Return ResourceManager.GetString("nameStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New password.
        '''</summary>
        Friend Shared ReadOnly Property newPassStr() As String
            Get
                Return ResourceManager.GetString("newPassStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Values.
        '''</summary>
        Friend Shared ReadOnly Property newStr() As String
            Get
                Return ResourceManager.GetString("newStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property pass() As String
            Get
                Return ResourceManager.GetString("pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property passColStr() As String
            Get
                Return ResourceManager.GetString("passColStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The password must have between 8 and 32 characters.
        '''</summary>
        Friend Shared ReadOnly Property passLenghStr() As String
            Get
                Return ResourceManager.GetString("passLenghStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password Recovery Questions.
        '''</summary>
        Friend Shared ReadOnly Property passRecQStr() As String
            Get
                Return ResourceManager.GetString("passRecQStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password successfully changed.
        '''</summary>
        Friend Shared ReadOnly Property passSuccStr() As String
            Get
                Return ResourceManager.GetString("passSuccStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone:.
        '''</summary>
        Friend Shared ReadOnly Property phoneStr() As String
            Get
                Return ResourceManager.GetString("phoneStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Profile.
        '''</summary>
        Friend Shared ReadOnly Property pro() As String
            Get
                Return ResourceManager.GetString("pro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Profile.
        '''</summary>
        Friend Shared ReadOnly Property proFormStr() As String
            Get
                Return ResourceManager.GetString("proFormStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change profile image.
        '''</summary>
        Friend Shared ReadOnly Property proImgFormStr() As String
            Get
                Return ResourceManager.GetString("proImgFormStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-type new password.
        '''</summary>
        Friend Shared ReadOnly Property reNewPassStr() As String
            Get
                Return ResourceManager.GetString("reNewPassStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secret Awnser:.
        '''</summary>
        Friend Shared ReadOnly Property secAStr() As String
            Get
                Return ResourceManager.GetString("secAStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secret Question:.
        '''</summary>
        Friend Shared ReadOnly Property secQStr() As String
            Get
                Return ResourceManager.GetString("secQStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select and image first.
        '''</summary>
        Friend Shared ReadOnly Property selImgStr() As String
            Get
                Return ResourceManager.GetString("selImgStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ajustes.
        '''</summary>
        Friend Shared ReadOnly Property settStr() As String
            Get
                Return ResourceManager.GetString("settStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Contact Information.
        '''</summary>
        Friend Shared ReadOnly Property showContInfStr() As String
            Get
                Return ResourceManager.GetString("showContInfStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show passwords.
        '''</summary>
        Friend Shared ReadOnly Property showPassChkStr() As String
            Get
                Return ResourceManager.GetString("showPassChkStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show password recovery options.
        '''</summary>
        Friend Shared ReadOnly Property showPassStr() As String
            Get
                Return ResourceManager.GetString("showPassStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show user level.
        '''</summary>
        Friend Shared ReadOnly Property showUserLvlStr() As String
            Get
                Return ResourceManager.GetString("showUserLvlStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iniciar la app.
        '''</summary>
        Friend Shared ReadOnly Property startStr() As String
            Get
                Return ResourceManager.GetString("startStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Surname.
        '''</summary>
        Friend Shared ReadOnly Property surnameColStr() As String
            Get
                Return ResourceManager.GetString("surnameColStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Surname:.
        '''</summary>
        Friend Shared ReadOnly Property surnameStr() As String
            Get
                Return ResourceManager.GetString("surnameStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User Management.
        '''</summary>
        Friend Shared ReadOnly Property userManFormStr() As String
            Get
                Return ResourceManager.GetString("userManFormStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Username.
        '''</summary>
        Friend Shared ReadOnly Property userName() As String
            Get
                Return ResourceManager.GetString("userName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property userNameColStr() As String
            Get
                Return ResourceManager.GetString("userNameColStr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wrong username or password.
        '''</summary>
        Friend Shared ReadOnly Property wrgPass() As String
            Get
                Return ResourceManager.GetString("wrgPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wrong password.
        '''</summary>
        Friend Shared ReadOnly Property wrgPassStr() As String
            Get
                Return ResourceManager.GetString("wrgPassStr", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
